"""empty message

Revision ID: 30fd6c394da9
Revises: 55758b93191c
Create Date: 2022-10-10 23:11:01.406802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30fd6c394da9'
down_revision = '55758b93191c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sa.VARCHAR(length=120), nullable=False))
    # ### end Alembic commands ###
