"""empty message

Revision ID: b17431bce90a
Revises: 8b696e068598
Create Date: 2022-10-15 21:59:40.525384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b17431bce90a'
down_revision = '8b696e068598'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('first_name', sa.String(length=120), nullable=False))
    op.add_column('users', sa.Column('middle_name', sa.String(length=120), nullable=False))
    op.add_column('users', sa.Column('last_name', sa.String(length=120), nullable=False))
    op.add_column('users', sa.Column('mobile_phone', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('Address', sa.String(length=120), nullable=False))
    op.create_unique_constraint(None, 'users', ['password'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'Address')
    op.drop_column('users', 'mobile_phone')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'middle_name')
    op.drop_column('users', 'first_name')
    # ### end Alembic commands ###
